# Generated by Django 5.1.4 on 2025-01-14 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('aDescripcion', models.TextField()),
                ('fFechaInicio', models.DateField()),
                ('fFechaFin', models.DateField()),
                ('dDireccion', models.TextField()),
                ('dLatitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dLongitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lGratuito', models.BooleanField(default=False)),
                ('aImagen', models.ImageField(blank=True, null=True, upload_to='eventos/imagenes/')),
                ('lAgendaVisible', models.BooleanField(default=True)),
                ('lActivo', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
