# Generated by Django 5.1.4 on 2025-01-15 02:20

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='aImagen',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.renombrar_archivo),
        ),
    ]
