# Generated by Django 5.1.4 on 2025-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_ddireccion_evento_dcp_evento_dcalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fFechaInicio',
            field=models.DateTimeField(),
        ),
    ]
