# Generated by Django 5.1.4 on 2025-03-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_ffechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fFechaFin',
            field=models.DateTimeField(),
        ),
    ]
