# Generated by Django 5.1.4 on 2025-03-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_registroevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroevento',
            name='escaneado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_eventos_escaneados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='fEscaneo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroevento',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('escaneado', 'Escaneado')], default='pendiente', max_length=10),
        ),
    ]
