# Generated by Django 5.1.4 on 2025-04-03 23:18

import django.db.models.deletion
import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_registroevento_escaneado_por_registroevento_fescaneo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=eventos.models.archivo_evento_upload_path, validators=[eventos.models.validar_extension_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='eventos.evento')),
            ],
        ),
    ]
