# Generated by Django 5.1.4 on 2025-05-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_archivoevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255, unique=True)),
                ('lActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.categoriaevento'),
        ),
    ]
