# Generated by Django 5.1.4 on 2025-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_categoriaevento_evento_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoevento',
            name='lActivo',
            field=models.BooleanField(default=True),
        ),
    ]
