# Generated by Django 5.1.4 on 2025-06-12 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_archivoevento_lactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNombre', models.CharField(max_length=255, unique=True)),
                ('lActivo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='eventos.categoriaevento')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.subcategoriaevento'),
        ),
    ]
