# Generated by Django 5.1.4 on 2025-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_subcategoriaevento_evento_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroevento',
            name='fRegistro',
            field=models.DateTimeField(),
        ),
    ]
