# Generated by Django 5.2.4 on 2025-10-05 17:22

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_alter_registroevento_fregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaevento',
            name='estilo_detalle_evento',
            field=models.CharField(choices=[('1', 'Estilo 1'), ('2', 'Estilo 2')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='categoriaevento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=eventos.models.categoria_logo_upload_path),
        ),
    ]
