# Generated by Django 5.2.4 on 2025-07-03 14:43

import django.db.models.deletion
import notificaciones.models
import utils.fechas
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=notificaciones.models.renombrar_archivo_notificacion)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('programada', 'Programada')], default='borrador', max_length=20)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(default=utils.fechas.ahora_mx)),
                ('fecha_modificacion', models.DateTimeField(default=utils.fechas.ahora_mx)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=notificaciones.models.renombrar_archivo_historial)),
                ('fecha_envio', models.DateTimeField()),
                ('hash_imagen', models.CharField(blank=True, max_length=64, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_historial', to='notificaciones.notificacion')),
            ],
            options={
                'verbose_name': 'Imagen de Historial',
                'verbose_name_plural': 'Imágenes de Historial',
                'unique_together': {('notificacion', 'fecha_envio')},
            },
        ),
        migrations.CreateModel(
            name='HistorialNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_original', models.CharField(max_length=200)),
                ('mensaje_original', models.TextField()),
                ('datos_adicionales_original', models.JSONField(blank=True, default=dict)),
                ('player_id', models.CharField(max_length=255)),
                ('fecha_envio', models.DateTimeField()),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('estado_entrega', models.CharField(choices=[('entregada', 'Entregada'), ('vista', 'Vista')], default='entregada', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=utils.fechas.ahora_mx)),
                ('fecha_modificacion', models.DateTimeField(default=utils.fechas.ahora_mx)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_notificaciones', to=settings.AUTH_USER_MODEL)),
                ('imagen_historial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='notificaciones.historialnotificacionimagen')),
                ('notificacion_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_envios', to='notificaciones.notificacion')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['usuario', '-fecha_envio'], name='notificacio_usuario_f4a5dc_idx'), models.Index(fields=['notificacion_referencia'], name='notificacio_notific_336eaf_idx'), models.Index(fields=['fecha_envio'], name='notificacio_fecha_e_cc4e41_idx')],
            },
        ),
    ]
