# Generated by Django 5.1.4 on 2025-01-15 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_alter_evento_aimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255, unique=True)),
                ('lActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('aDescripcion', models.TextField()),
                ('nCosto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nCapacidad', models.PositiveIntegerField()),
                ('nLugaresDisponibles', models.PositiveIntegerField()),
                ('fFechaHoraInicio', models.DateTimeField()),
                ('fFechaHoraFin', models.DateTimeField()),
                ('lAcompañantes', models.BooleanField(default=False)),
                ('nAcompañantes', models.PositiveIntegerField(default=0)),
                ('lActivo', models.BooleanField(default=True)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='eventos.evento')),
                ('idTipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='actividades.tipoactividad')),
            ],
        ),
    ]
