# Generated by Django 5.1.4 on 2025-03-17 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_registroactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcompañanteActividad',
            fields=[
                ('idAcompaniante', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompañantes_registrados', to='actividades.registroactividad')),
            ],
        ),
    ]
