# Generated by Django 5.1.4 on 2025-03-19 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_acompañanteactividad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraActividad',
            fields=[
                ('idCompra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Tarjeta'), ('openpay', 'OpenPay')], max_length=10)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=10)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_actividades', to='actividades.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_actividades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
