# Generated by Django 5.1.4 on 2025-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_registroactividad_escaneado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraactividad',
            name='fecha_compra',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='fRegistro',
            field=models.DateTimeField(),
        ),
    ]
