# Generated by Django 5.1.4 on 2025-02-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0003_remove_evento_ddireccion_evento_dcp_evento_dcalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('idStand', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('aImagen', models.ImageField(blank=True, null=True, upload_to='stands/imagenes/')),
                ('nNumeroStand', models.PositiveIntegerField()),
                ('lActivo', models.BooleanField(default=True)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands', to='eventos.evento')),
            ],
        ),
    ]
