# Generated by Django 5.1.4 on 2025-02-24 22:56

import django.db.models.deletion
import stands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='aImagen',
            field=models.ImageField(blank=True, null=True, upload_to=stands.models.renombrar_archivo),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('aImagen', models.ImageField(blank=True, null=True, upload_to=stands.models.renombrar_archivo_productos)),
                ('nPrecio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idStand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='stands.stand')),
            ],
        ),
    ]
