# Generated by Django 5.1.4 on 2025-02-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0002_alter_stand_aimagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='lActivo',
            field=models.BooleanField(default=True),
        ),
    ]
