# Generated by Django 5.1.4 on 2025-03-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0003_producto_lactivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='aDescripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='aNombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stand',
            name='nNumeroStand',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
