# Generated by Django 5.1.4 on 2025-03-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0004_stand_adescripcion_alter_stand_anombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrostand',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fRegistro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('escaneado', 'Escaneado')], default='pendiente', max_length=10)),
                ('fEscaneo', models.DateTimeField(blank=True, null=True)),
                ('escaneado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_stands_escaneados', to=settings.AUTH_USER_MODEL)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_registrados', to='stands.stand')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stands_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'stand')},
            },
        ),
    ]
