# Generated by Django 5.1.4 on 2025-04-02 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0005_registrostand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='representante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stands_representados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CitaStand',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('aStatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fFechaHora', models.DateTimeField()),
                ('aMensaje', models.TextField(blank=True, null=True)),
                ('idStand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='stands.stand')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
