# Generated by Django 5.1.4 on 2025-04-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0006_stand_representante_citastand'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='fue_creado_con_representante',
            field=models.BooleanField(default=False),
        ),
    ]
