# Generated by Django 5.1.4 on 2025-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0007_stand_fue_creado_con_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='citastand',
            name='aNotas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
