# Generated by Django 5.1.4 on 2025-04-03 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0008_citastand_anotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioCita',
            fields=[
                ('idHorario', models.AutoField(primary_key=True, serialize=False)),
                ('fFechaHora', models.DateTimeField()),
                ('idStand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='stands.stand')),
            ],
            options={
                'ordering': ['fFechaHora'],
                'unique_together': {('idStand', 'fFechaHora')},
            },
        ),
    ]
