# Generated by Django 5.1.4 on 2025-04-04 00:38

import django.db.models.deletion
import stands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0009_horariocita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=stands.models.archivo_stand_upload_path, validators=[stands.models.validar_extension_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='stands.stand')),
            ],
        ),
    ]
