# Generated by Django 5.1.4 on 2025-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0010_archivostand'),
    ]

    operations = [
        migrations.AddField(
            model_name='stand',
            name='lPagoPresencialPermitido',
            field=models.BooleanField(default=False, help_text='¿Se permite el pago presencial de las citas?'),
        ),
        migrations.AddField(
            model_name='stand',
            name='nCostoCita',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de cada cita. Dejar en 0 si serán gratuitas.', max_digits=10),
        ),
    ]
