# Generated by Django 5.1.4 on 2025-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0011_stand_lpagopresencialpermitido_stand_ncostocita'),
    ]

    operations = [
        migrations.AddField(
            model_name='citastand',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='citastand',
            name='monto_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='citastand',
            name='status_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
