# Generated by Django 5.1.4 on 2025-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0012_citastand_metodo_pago_citastand_monto_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='fue_creado_con_representante',
        ),
        migrations.AddField(
            model_name='archivostand',
            name='lActivo',
            field=models.BooleanField(default=True),
        ),
    ]
