# Generated by Django 5.1.4 on 2025-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0013_remove_stand_fue_creado_con_representante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrostand',
            name='fRegistro',
            field=models.DateTimeField(),
        ),
    ]
