# Generated by Django 5.2.4 on 2025-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aportador',
            fields=[
                ('idAportador', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('aEmail', models.EmailField(max_length=255)),
                ('lActivo', models.BooleanField(default=True)),
            ],
        ),
    ]
