# Generated by Django 5.2.4 on 2025-07-08 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportaciones', '0001_initial'),
        ('eventos', '0012_alter_registroevento_fregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportacion',
            fields=[
                ('idAportacion', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('aDescripcion', models.TextField()),
                ('eEstado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagada', 'Pagada')], default='pendiente', max_length=10)),
                ('fCreacion', models.DateTimeField(auto_now_add=True)),
                ('fModificacion', models.DateTimeField(auto_now=True)),
                ('fPago', models.DateTimeField(blank=True, null=True)),
                ('lActivo', models.BooleanField(default=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('paypal', 'PayPal'), ('stripe', 'Tarjeta')], max_length=20, null=True)),
                ('idAportador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportaciones', to='aportaciones.aportador')),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportaciones', to='eventos.evento')),
            ],
        ),
    ]
