# Generated by Django 5.2.4 on 2025-07-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aportaciones', '0002_aportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aportacion',
            name='monto_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
