# Generated by Django 5.2.4 on 2025-07-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Prompt general', max_length=100)),
                ('seccion_fija', models.TextField(default='Eres un asistente virtual diseñado exclusivamente para ayudar a los usuarios de RegistroClustertim, la plataforma web oficial de Clustertim para la gestión de eventos.\n\nLimítate estrictamente a temas relacionados con RegistroClustertim. No des información sobre otros temas ni inventes respuestas si no tienes datos suficientes.\n\nUsa un tono profesional, claro y cordial.\n\nSi no tienes información suficiente sobre una pregunta, responde: "Actualmente no dispongo de esa información. Por favor revisa la plataforma o contacta al soporte de Clustertim."', editable=False, help_text='Esta sección es fija y no puede ser editada.')),
                ('seccion_editable', models.TextField(default='Los usuarios deben crear una cuenta para comprar entradas o registrarse en eventos gratuitos.\nCada cuenta tiene un código QR único que sirve como acceso a los eventos.\nLos métodos de pago disponibles son tarjeta de crédito/débito, PayPal o depósito bancario.\nLos eventos pueden incluir conferencistas, patrocinadores y stands. Algunos stands están asociados a patrocinadores.', help_text='Puedes modificar esta sección según se requiera.')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
