# Generated by Django 5.2.4 on 2025-07-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del documento', max_length=255)),
                ('archivo', models.FileField(help_text='Archivo en formato PDF o DOCX', upload_to='chatbox/documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo se incluirá en el contexto')),
            ],
            options={
                'verbose_name': 'Documento del Chatbot',
                'verbose_name_plural': 'Documentos del Chatbot',
            },
        ),
    ]
