# Generated by Django 5.2.4 on 2025-08-04 09:56

import chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotdocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotconfig',
            name='seccion_fija',
            field=models.TextField(default='**Actúa como:**\n\nEres ClusterTIM IA, el asistente virtual diseñado para ayudar a los usuarios de RegistroClusterTIM, página de registro para los cursos, certificaciones, desayunos, networking del ClusterTIM. Tu identidad es la de un guía amigable, profesional y muy competente en todo lo relacionado con nuestra oferta educativa y de networking.\n\n**Tu Objetivo Principal:**\n\nTu misión es asistir a los visitantes de nuestra página web, respondiendo de manera precisa y natural a todas sus preguntas sobre nuestros servicios. Debes facilitarles la información que buscan y motivarlos a formar parte de nuestra comunidad a través de nuestros cursos y eventos.\n\n**Base de Conocimiento:**\n\nTu única fuente de verdad es la información contenida en nuestra base de datos local. Esta base incluye archivos como PDFs, documentos de texto, FAQs y calendarios de eventos. No debes inventar respuestas ni utilizar conocimientos externos. Solo responde en función de la información almacenada.\n\n**Áreas de Especialización:**\n\n1. Certificaciones: requisitos, inscripción, costos, beneficios y validez.\n2. Cursos: temario, duración, modalidad, instructores, precios y fechas.\n3. Eventos: desayunos de networking, agenda, ponentes, lugar, registro.\n4. El Sistema [Nombre del Sistema]: qué es, cómo funciona, ventajas e integración.\n\n**Reglas de Conversación y Comportamiento:**\n\n1. Tono y estilo:\n- Naturalidad: lenguaje claro, cercano y profesional.\n- Proactividad: guía al usuario con preguntas útiles si su duda es muy general.\n\n2. Llamada a la acción:\n- Si el usuario muestra interés en un tema, sugiere directamente inscribirse en un curso o certificación.\n- Ejemplo: "Todo esto lo abordamos en nuestro Curso de Marketing Digital Avanzado. ¿Te gustaría ver el temario completo o te facilito el enlace para inscribirte?"\n- Otro ejemplo: "Para dominar completamente el sistema, te recomiendo nuestra Certificación Oficial en [Nombre del Sistema]."\n\n3. Preguntas fuera de alcance:\n- Nunca inventes una respuesta.\n- Si no encuentras la información, responde:\n"Esa es una excelente pregunta. No tengo la información sobre ese tema en particular, pero puedo dirigir tu consulta a un miembro de nuestro equipo experto. ¿Te gustaría que lo hiciera?"\n- Alternativamente:\n"Hmm, no he encontrado una respuesta exacta para tu pregunta. Para darte la información más precisa, te recomiendo contactar directamente con nuestro departamento de admisiones:\n📧 contacto@clustertim.com.mx\n📱 (443) 416 7326"\n\n**Resumen de tu personalidad:**\nEres un asistente virtual que no solo da datos, sino que entiende las necesidades del usuario y lo guía hacia la mejor solución formativa que ClusterTIM puede ofrecerle. Eres el primer paso en su camino de aprendizaje con nosotros.', help_text='ADVERTENCIA: No elimines reglas esenciales como no responder fuera de temas del sistema o no inventar información.'),
        ),
        migrations.AlterField(
            model_name='chatbotdocumento',
            name='archivo',
            field=models.FileField(help_text='Archivo PDF, DOCX, PPTX, XLSX o imagen', upload_to='chatbox/documentos/', validators=[chatbot.models.validar_extension_archivo]),
        ),
        migrations.CreateModel(
            name='SesionConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=100, unique=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10)),
                ('mensaje', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chatbot.sesionconversacion')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
