# Generated by Django 5.1.4 on 2025-05-21 18:32

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to=web.models.banner_imagen_upload_path)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
