# Generated by Django 5.1.4 on 2025-05-21 19:39

import web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=web.models.archivo_upload_path, validators=[web.models.validar_extension_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
