# Generated by Django 5.1.4 on 2025-06-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_archivopagina_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopagina',
            name='lActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bannerprincipal',
            name='lActivo',
            field=models.BooleanField(default=True),
        ),
    ]
