# Generated by Django 5.1.4 on 2025-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_archivopagina_lactivo_bannerprincipal_lactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPagoEfectivoConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aNombreBanco', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('aNombreBeneficiario', models.CharField(max_length=255, verbose_name='Nombre del beneficiario')),
                ('aNumeroCuenta', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('aClabe', models.CharField(max_length=50, verbose_name='CLABE interbancaria')),
                ('lActivo', models.BooleanField(default=True, help_text='Indica si este método está disponible actualmente')),
            ],
        ),
    ]
