# Generated by Django 5.1.5 on 2025-02-21 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('idPatrocinador', models.AutoField(primary_key=True, serialize=False)),
                ('aBiografia', models.TextField()),
                ('aTelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('aWhatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('aEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('aFacebook', models.URLField(blank=True, null=True)),
                ('aInstagram', models.URLField(blank=True, null=True)),
                ('aTwitter', models.URLField(blank=True, null=True)),
                ('aSitioWeb', models.URLField(blank=True, null=True)),
                ('aFoto', models.ImageField(blank=True, null=True, upload_to='patrocinadores/fotos/')),
                ('lActivo', models.BooleanField(default=True)),
                ('idStand', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrocinador', to='stands.stand')),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrocinador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
