# Generated by Django 5.1.4 on 2025-03-03 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_remove_evento_ddireccion_evento_dcp_evento_dcalle_and_more'),
        ('patrocinadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='idEvento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patrocinadores', to='eventos.evento'),
        ),
    ]
