# Generated by Django 5.1.4 on 2025-03-07 02:37

import patrocinadores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrocinadores', '0002_patrocinador_idevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinador',
            name='aFoto',
            field=models.ImageField(blank=True, null=True, upload_to=patrocinadores.models.renombrar_archivo),
        ),
    ]
