# Generated by Django 5.1.4 on 2025-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrocinadores', '0003_alter_patrocinador_afoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='aNombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
