# Generated by Django 5.1.5 on 2025-02-13 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0002_actividad_dcp_actividad_dcalle_actividad_dciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expositor',
            fields=[
                ('idExpositor', models.AutoField(primary_key=True, serialize=False)),
                ('aBiografia', models.TextField()),
                ('aTelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('aWhatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('aEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('aFacebook', models.URLField(blank=True, null=True)),
                ('aInstagram', models.URLField(blank=True, null=True)),
                ('aTwitter', models.URLField(blank=True, null=True)),
                ('aSitioWeb', models.URLField(blank=True, null=True)),
                ('aFoto', models.ImageField(blank=True, null=True, upload_to='expositores/fotos/')),
                ('lActivo', models.BooleanField(default=True)),
                ('idUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expositor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CitaExpositor',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('aStatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fFechaHora', models.DateTimeField()),
                ('aMensaje', models.TextField(blank=True, null=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('idExpositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='expositores.expositor')),
            ],
        ),
        migrations.CreateModel(
            name='ExpositorActividad',
            fields=[
                ('idExpositorActividad', models.AutoField(primary_key=True, serialize=False)),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expositores', to='actividades.actividad')),
                ('idExpositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='expositores.expositor')),
            ],
        ),
    ]
