# Generated by Django 5.1.4 on 2025-05-21 20:04

import django.db.models.deletion
import expositores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositores', '0002_delete_citaexpositor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoExpositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=expositores.models.archivo_expositor_upload_path, validators=[expositores.models.validar_extension_archivo])),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('expositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='expositores.expositor')),
            ],
        ),
    ]
