# Generated by Django 5.1.4 on 2025-06-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expositores', '0003_archivoexpositor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expositor',
            name='idUsuario',
        ),
        migrations.AddField(
            model_name='archivoexpositor',
            name='lActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expositor',
            name='aNombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
