# Generated by Django 5.1.5 on 2025-02-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('patrocinador', 'Patrocinador'), ('socio', 'Socio'), ('no socio', 'No Socio'), ('acompañante', 'Acompañante'), ('administrador', 'Administrador'), ('gestor', 'Gestor'), ('expositor', 'Expositor')], default='no socio', max_length=50),
        ),
    ]
