# Generated by Django 5.1.4 on 2025-03-10 22:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_token_verificacion_usuario_verificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_verificacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
