# Generated by Django 5.1.4 on 2025-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_token_verificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aEmpresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aRFC',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
