# Generated by Django 5.1.4 on 2025-03-19 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_registroactividad_escaneado_por_and_more'),
        ('eventos', '0007_registroevento_escaneado_por_registroevento_fescaneo_and_more'),
        ('stands', '0005_registrostand'),
        ('usuarios', '0005_usuario_aempresa_usuario_arfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('patrocinador', 'Patrocinador'), ('socio', 'Socio'), ('no socio', 'No Socio'), ('acompañante', 'Acompañante'), ('administrador', 'Administrador'), ('gestor', 'Gestor'), ('expositor', 'Expositor'), ('lector', 'Lector')], default='no socio', max_length=50),
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lector', models.CharField(choices=[('general', 'Lector General'), ('evento_completo', 'Lector de Evento Completo'), ('evento_especifico', 'Lector de Evento Específico'), ('actividades_completo', 'Lector de Actividades Completo'), ('actividades_especifico', 'Lector de Actividades Específico'), ('stands_completo', 'Lector de Stands Completo'), ('stands_especifico', 'Lector de Stands Específico'), ('stand_especifico', 'Lector de Stand Específico')], max_length=50)),
                ('actividades', models.ManyToManyField(blank=True, related_name='lectores', to='actividades.actividad')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectores', to='eventos.evento')),
                ('stands', models.ManyToManyField(blank=True, related_name='lectores', to='stands.stand')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
