# Generated by Django 5.1.4 on 2025-03-19 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0005_registrostand'),
        ('usuarios', '0006_alter_usuario_tipo_usuario_lector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='stands',
        ),
        migrations.AddField(
            model_name='lector',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectores_stand', to='stands.stand'),
        ),
    ]
