# Generated by Django 5.1.4 on 2025-03-26 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_registroevento_escaneado_por_registroevento_fescaneo_and_more'),
        ('usuarios', '0008_usuario_aanadic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('patrocinador', 'Patrocinador'), ('socio', 'Socio'), ('no socio', 'No Socio'), ('acompañante', 'Acompañante'), ('administrador', 'Administrador'), ('gestor', 'Gestor'), ('expositor', 'Expositor'), ('lector', 'Lector'), ('super administrador', 'Super Administrador'), ('administrador auxiliar', 'Administrador Auxiliar')], default='no socio', max_length=50),
        ),
        migrations.CreateModel(
            name='EventoAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('auxiliar', models.ForeignKey(limit_choices_to={'tipo_usuario': 'administrador auxiliar'}, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliares_asignados', to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Evento asignado a auxiliar',
                'verbose_name_plural': 'Eventos asignados a auxiliares',
                'unique_together': {('auxiliar', 'evento')},
            },
        ),
    ]
