# Generated by Django 5.1.4 on 2025-04-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_tipo_usuario_eventoasignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('patrocinador', 'Patrocinador'), ('socio', 'Socio'), ('no socio', 'No Socio'), ('acompañante', 'Acompañante'), ('administrador', 'Administrador'), ('gestor', 'Gestor'), ('stand', 'Stand'), ('lector', 'Lector'), ('super administrador', 'Super Administrador'), ('administrador auxiliar', 'Administrador Auxiliar')], default='no socio', max_length=50),
        ),
    ]
