# Generated by Django 5.1.4 on 2025-04-13 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionExportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activar_exportacion', models.BooleanField(default=False)),
                ('intervalo_minutos', models.PositiveIntegerField(default=60)),
                ('exportar_eventos', models.BooleanField(default=False)),
                ('exportar_actividades', models.BooleanField(default=False)),
                ('exportar_stands', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_exportacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
