# Generated by Django 5.1.4 on 2025-04-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_configuracionexportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aApellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
