# Generated by Django 5.1.4 on 2025-05-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_usuario_aapellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aRFC',
        ),
    ]
