# Generated by Django 5.1.4 on 2025-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_usuario_arfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='aTelefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='aWhatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
