# Generated by Django 5.1.4 on 2025-06-14 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_usuario_atelefono_usuario_awhatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='stand',
        ),
        migrations.RemoveField(
            model_name='lector',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='aAnadic',
            field=models.CharField(blank=True, choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Estado de México', 'Estado de México'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoacán', 'Michoacán'), ('Nacional', 'Nacional'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('super_administrador', 'Super Administrador')], default='cliente', max_length=50),
        ),
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=50)),
                ('alcance', models.CharField(blank=True, choices=[('estado', 'Estado ANADIC'), ('evento', 'Evento específico'), ('stand', 'Stand específico'), ('actividad', 'Actividad específica')], max_length=50, null=True)),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'categoria', 'accion', 'alcance', 'valor')},
            },
        ),
        migrations.DeleteModel(
            name='EventoAsignado',
        ),
        migrations.DeleteModel(
            name='Lector',
        ),
    ]
