# Generated by Django 5.1.4 on 2025-06-19 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_remove_lector_evento_remove_lector_stand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionGuardada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dCalle', models.CharField(default='No especificado', max_length=255)),
                ('dNumero', models.CharField(default='S/N', max_length=10)),
                ('dColonia', models.CharField(default='No especificado', max_length=255)),
                ('dCiudad', models.CharField(default='No especificado', max_length=255)),
                ('dEstado', models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Estado de México', 'Estado de México'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], default='No especificado', max_length=50)),
                ('dCP', models.CharField(default='00000', max_length=10)),
                ('dLatitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dLongitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lPrivada', models.BooleanField(default=True, help_text='Si está activado, solo el usuario dueño puede usar esta dirección.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_guardadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
