# Generated by Django 5.2.4 on 2025-07-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_pushsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
