# Generated by Django 5.1.4 on 2025-02-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0002_actividad_dcp_actividad_dcalle_actividad_dciudad_and_more'),
        ('eventos', '0003_remove_evento_ddireccion_evento_dcp_evento_dcalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('idEntrada', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('nCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nCantidad', models.PositiveIntegerField()),
                ('nVendidas', models.PositiveIntegerField(default=0)),
                ('lActivo', models.BooleanField(default=True)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_incluidas', to='actividades.actividad')),
                ('idEntrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_incluidas', to='entradas.entrada')),
            ],
        ),
    ]
