# Generated by Django 5.1.4 on 2025-05-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_compraentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aCodigo', models.CharField(max_length=50, unique=True)),
                ('eTipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('cantidad', 'Cantidad fija')], max_length=20)),
                ('nValor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nLimiteUso', models.PositiveIntegerField(blank=True, null=True)),
                ('nUsados', models.PositiveIntegerField(default=0)),
                ('lActivo', models.BooleanField(default=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones', to='entradas.entrada')),
            ],
        ),
    ]
