# Generated by Django 5.1.4 on 2025-05-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0003_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraentrada',
            name='metodo_pago',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Tarjeta'), ('openpay', 'OpenPay'), ('gratuito_cuponado', 'Gratuito (Cupón)')], max_length=18),
        ),
    ]
