# Generated by Django 5.1.4 on 2025-05-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0004_alter_compraentrada_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraentrada',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entradas.cupon'),
        ),
    ]
