# Generated by Django 5.1.4 on 2025-06-13 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0005_compraentrada_cupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compraentrada',
            name='nCantidad',
            field=models.PositiveIntegerField(default=1, help_text='Número de entradas compradas.'),
        ),
        migrations.AddField(
            model_name='cupon',
            name='lAplicaTotal',
            field=models.BooleanField(default=False, help_text='¿El cupón se aplica al total (todas las entradas) o solo a una unidad?'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='lMultiple',
            field=models.BooleanField(default=False, help_text='Permite comprar más de una entrada en una sola compra.'),
        ),
        migrations.CreateModel(
            name='CodigoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('activado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_usados', to=settings.AUTH_USER_MODEL)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='entradas.compraentrada')),
            ],
        ),
    ]
