# Generated by Django 5.1.4 on 2025-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0006_compraentrada_ncantidad_cupon_laplicatotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraentrada',
            name='fecha_compra',
            field=models.DateTimeField(),
        ),
    ]
