# Generated by Django 5.1.4 on 2025-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0007_alter_compraentrada_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraentrada',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='compras/comprobantes/'),
        ),
        migrations.AddField(
            model_name='compraentrada',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compraentrada',
            name='metodo_pago',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Tarjeta'), ('openpay', 'OpenPay'), ('efectivo', 'Efectivo'), ('gratuito_cuponado', 'Gratuito (Cupón)')], max_length=18),
        ),
        migrations.AlterField(
            model_name='compraentrada',
            name='nCantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
