# Generated by Django 5.1.4 on 2025-02-10 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0002_actividad_dcp_actividad_dcalle_actividad_dciudad_and_more'),
        ('eventos', '0003_remove_evento_ddireccion_evento_dcp_evento_dcalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idAgenda', models.AutoField(primary_key=True, serialize=False)),
                ('aNombre', models.CharField(max_length=255)),
                ('lVisible', models.BooleanField(default=True)),
                ('lActivo', models.BooleanField(default=True)),
                ('idEvento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaActividades',
            fields=[
                ('idAgendaActividad', models.AutoField(primary_key=True, serialize=False)),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_actividades', to='actividades.actividad')),
                ('idAgenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_actividades', to='agendas.agenda')),
            ],
            options={
                'unique_together': {('idAgenda', 'idActividad')},
            },
        ),
    ]
